

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL.EF
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class bePartnerCentralDatabaseEntities : DbContext
{
    public bePartnerCentralDatabaseEntities()
        : base("name=bePartnerCentralDatabaseEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<Entrepreneur> Entrepreneurs { get; set; }

    public virtual DbSet<Idea> Ideas { get; set; }

    public virtual DbSet<Investor> Investors { get; set; }

    public virtual DbSet<Message> Messages { get; set; }

    public virtual DbSet<Offer> Offers { get; set; }

    public virtual DbSet<Report> Reports { get; set; }

    public virtual DbSet<Token> Tokens { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Admin> Admins { get; set; }

    public virtual DbSet<Notice> Notices { get; set; }

}

}

